trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - "*"

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: echo "🚀 Pull Request Pipeline Started"
  displayName: "Start Message"

- script: |
    echo "✅ This is a PR test build."
    echo "🎯 Your Azure DevOps integration works!"
  displayName: "Run Test Steps"
