project_config:
  app_name: "MemoriAI Cognitive Service"
  version: "1.0"
  description: "A cognitive and memory-assistive chatbot with long-term and short-term memory integration."

directories:
  db_path: "data/chatbot.db"
  vectordb_dir: "data/vectordb"

llm_config:
  chat_model: "gpt-4o"
  summary_model: "gpt-3.5-turbo"
  rag_model: "gpt-4o-mini"
  temperature: 0.0
  fallback_model: "gpt-4o-mini"

chat_history_config:
  max_history_pairs: 2
  max_characters: 1000
  max_tokens: 2000

agent_config:
  max_function_calls: 3

vectordb_config:
  collections:
    cognitive_memories: "cognitive_memories"
    identity_links: "identity_links"
    personal_facts: "personal_facts"
  embedding_model: "text-embedding-3-small"
  k: 3
